
name: Deployment
on:
  push:
    branches: ["master", "issue-11-housekeeping"]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy to K19-IV
    environment:
      name: k19-iv
      url: "https://famdb.folkarps.com"
    runs-on: ubuntu-latest
    steps:
      - name: Updating live site with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ENV_SSH_HOST }}
          username: ${{ secrets.ENV_SSH_USER }}
          key: ${{ secrets.ENV_SSH_KEY }}
          script_stop: true
          script: |
            cd ~/FAMDB

            echo "Backing up database"
            mkdir -p backups.db
            sqlite3 famdb.db ".backup backups.db/famdb-$(date --iso-8601=minutes)-$(git describe --always).db"
            
            echo "Updating code"
            git fetch --prune
            echo git checkout ${{ github.sha }}
            
            echo "Reloading Apache"
            echo sudo systemctl reload apache2